language: php
php:
- '7.0'
addons:
  ssh_known_hosts: 46.101.18.83
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead;'
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate
before_deploy:
- openssl aes-256-cbc -K $encrypted_499e418efa07_key -iv $encrypted_499e418efa07_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $DEPLOY_USER@$DEPLOY_IP:/var/www/$DEPLOY_DIR
  on:
    branch: 0.1/release
services:
- mysql
env:
  global:
  - secure: eDk2LZ2lLmERiWl7rbnVrmtNgjWxqIKS7wAF8W5wydP0wg9KhogtBtT4RFpw9riV9kcnZvwDahNeAFKbdTSgDE4mhFOM2BENRyIQu2VclnO+alTIfEtAqyywRIgr9KL3VCgTDsDfD9lwnGaz07obyG8BX6DbMxypbSfecXYS2vG6FOBGEE5FQYmchdU38haGwr5OmGbqvuDM21Lf9HuZpdLhiCRfaXah7ca5+P4I2LTBSjIknq+JmqbMqzX4hdaaWUEP473givLaKYzCKI6P8MCgBp0bbpM8k2yAPGYbnHmG8RZbzYxXft44iyNh3WFWVpkHjFgG2OIujK+wyPJagksk457/PqMG0hcR29FfD5hzWJ8L6JNLjpgZPWysd3yoyrXKEsiyJmORBZxs31CBZJa7VjFIGXuZx8Hk7kGu6ogBF8+KJwRgGGNfDF5S9OZpmJMOu/dTDOW1PY5O/SAOwszQxnbQH4jvXuDxCWPC0yTDBtKO/Sjiw3FFhgz6yo+KdniCrqUqB44iGZXRlWRP/dkVnouT5cNyiItubFRTZqIeVx9bkRKYcou8GhfmUaXpsOCwqHh6+PBlemT0SU+SEaDO5Wvu+sf18zDY1cCgMzFFh19bqQNSM1MPCno3VdMIeYts2n7VFUbg1oOvzFOQwHy094f5CT/v5DNPW+kCNMk=
  - secure: n74KHYjWGzALDfEMFB13CdrBv7Jco+patc3mFCVTqqGcANeUdTQcNU5QYcrfYkrgIhWjGLLKz320bN9Rw90xKdck1cy331YoN9MUnBCwTAW2zEMZ4qUB6K7ZWaP8NipphmtU35dVIkT16ailgkCyf9XHJ6aeCcVAd3YCg/xTaJI58TX3Fi4vghHNs6+nHUACHSJqfVu99hQiB95vF17HCr32EoKYdwHC2MhKjoLv0mIT+hTF2Cumy/Ssfpn35qIN5Q7uD5BASLxGCjWLfIbORSlsiETZ0PxWUu3EbR+n4HAb7Wd8UVult2/EVl5mrQPVDTBUfGWoNurMFvogEmoh7lHvYnWPmM8iQTLlrblcYn5T7f+w7q7YDbpnUfP+2o29MJYNq5Xru1D9f0LD/Qe/HcbRayogfUFuJYFg3oVKzvBPWacQa12Ss8plifxoC1TqgG1lay83T73EUq6ha4KXmvTvq6Xg/kd8e8HHs730UzV1aw5KjmN8sbbfHqkLbyWDXqIhpiWZr5+h1F6f0F0mc4OQvI411AyPo3EKRWwIjGNs9VCuIhGSS5pV312M6NU4Y+5smQWxsSKOKYY0o+W5pKNnnjwRMKP3XsYRsbeZEFcJacxM7dh4u9O7WZ8LtXCPABcjvYcvsUDzjmzb5kXsJhVA5VFYVXfvwsZTTrzlATI=
  - secure: I8NFehvm1l5dyETD6JqnBJvXFY92J6YS5csnYJaP5cyvQLQrQz0M+MDONiwxa56AdQO/Ih1i7eurimFprkLD3+B6CQJ/C0UTENlcs+MEOLalyu+hNKw+RwA46/JCUM5oiFYxyoG76mJHKTd3Yx/jMh0CiFdyGZpLM1kMKPcbYXWs+TobfwsncDCwagDJIsftBRmrZvlsY9uE4mQResTcPNbl+FD78JAob5Rwcy9zHTmObfN/VoFdMuVQhzBdNStp05nW7EGfLjjrhKr+fMTaRSmMs5MIhd7sxgCqi5qkcpEOE8kFRdhNrgsrWjBy/5+gFqCMKzxyUjBYa/9+ziumnOhPQlTg8OuqrOVOGqPznFjVFXmegR+FTmBkzQ9Tv+7bB+VeFQF6PUyVipDZZc53dyTyBRVTgCSwNN1NTChyKNUFCYX5XqrwkGjC88t/bKcO5CaFzm2kcsYpLikT0NgGc34Fj13OTYUzXQ1m42kY8x37Pl6q+cyJW7gC/WIxEUxngQ3onIAzA+irsVo+n8j1delBqHz2+lbq7zUV4sk7+oz4psOf702Wkm3oYnhzgmZB2od4d4uyxrYc9deyjTa/uN1U2nXFEHAZ4LZ5GX/s4X3GCfyYk2wbDdhakfOMhJm7kbGltgTIdjFwlNEyyKSDk4TCoQUNkuLsNZgHiJusV1E=
