language: php
php:
- '7.2'
sudo: required
dist: trusty
addons:
  ssh_known_hosts: 206.189.122.208
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead;'
- composer install --no-interaction
- php artisan key:generate
- php artisan passport:keys
- php artisan migrate --seed --force
- php artisan serve &
before_deploy:
- openssl aes-256-cbc -K $encrypted_f8d9f1054808_key -iv $encrypted_f8d9f1054808_iv
  -in staging_rsa.enc -out staging_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 staging_rsa
- ssh-add staging_rsa
deploy:
  # Deploy to staging.
  - provider: script
    skip_cleanup: true
    script: rsync -r --exclude storage --delete-after --quiet $TRAVIS_BUILD_DIR/* $STAGING_USER@$STAGING_IP:/var/www/$STAGING_DIR
    on:
      branch: 1.7/1377-retarget-travis-at-new-staging-server
  # Create production release tarball.
  - provider: script
    skip_cleanup: true
    script: tar -czf $TRAVIS_TAG.tar.gz ARCVService && scp $TRAVIS_TAG.tar.gz $STAGING_USER@$STAGING_IP:/home/$STAGING_USER/releases/service
    on:
      tags: true
services:
- mysql
env:
  global:
  - secure: b+QCBd/bBxucU+Ne1vQm8/0IixyOyP/fj5Xsh06LQXiFMXPvg8mqjKW0J98zJj+WlwKjZhsovbjN8j4JSaxPtkyrNiP0tuJhRvjzVauZHWFrgrvsP/oTaGjrkRdSYQqQwle+AtZwysY23VpU3wU9pKQ36bkA8AVYslggbTXfQ+aaPmAPamvJ3c0xLpnLJiM4yHuVyKKa3K793K6idiEoTZRDVB5065jOWs4YHzEDGMljJB3JTCOh4PW2iHtCsQ5XAmVXs6mlHb1Nc6inF9BSdmzaKBgoQRezD5cYAy9pmYc5XiCOF++FC4utTLhajv3pFHWS6vKRMcatch5aXFWmsmgkz/Kt/0ZMH2w2+qbGX2CFkqvDrdmbPHrykO2J1Tu+yQ9UzQpEOKi1IFGuoJ33Ku09Fjavz6hCsx85Sf1NVeFgZ0wWkK6ZCJwXHnw+YJZH77qN8Kc9thk+1f2opsizAEcMRZmKQ3oMU6xJ4BdF2rkh4WB+p9RhyyhJwcHQ6Px31vcohIrzBwTt0abmMTogMWAeLXnKwFeZ8vwX4Y+Z2R3chI0CjSJD9mDTuA1GTqjigbhOZxwAfV62fBdjG3uuuFTYLoQIyftUk821Qfpvzg/qyTKOZanvdrPE4x6nntwHZBqOgTDMoAd26sRUtCfqPIWZvY0lSynqmy+n3l93ntM=
  - secure: i2qL+r1rCPqiWaBLxTfsvEP9jEfW4iDljahwYpt3pw8F/E2bFoWXYtTIxW9EXUBP6fM44uSwGVkiz0pHCi88h9KHoUVYx0sxYhuJk7n4o+SVk7YglL4+PHqLy4t+Ouq5c1l94IA9nfiO91L4SztM0gW+qrFOJQ+nyqUjdKkFcyyNLjTPkIUrAoyAsN4lPxG3bHz13ppU+4qO9WFzszG/ATJNcCPss+6nRAgFAk788V+l6J0apl12ydHx9qrhm18UipYGVi5MmdYoZgHKtM4V/sAqcAf17SWEOa2U9SAepkeCHPMFNJiLtTtzshaD1DPrjtABXSRVjZ0TKDxQLOneRp0WBNnpJo/BR2U+A3zPXYI5rUDqYEShqyrpdsrP5L0Uq0whkX+E/rYwHvuGR9EFM8sKf8sNNJ87yAeO5R9tcD6FjCq/5PHncWed/4h6brs7QQgu1QYlAh23/S39q9o6ZfphWpP0hmkBFKdo5HX1hfwdoHKO5f8Tw7VYQxq/YXc9PquMdQv9alx7yOV6c+f/s5mnDA/p1SSQqMOImqyTWeSQSAswiGSgoKhhbgMG5KtGc/e4wGzmO9U+VxaB3PPwDixZeZOuGjw9dfT4UAUI/NZX5FQnLdP4ZvkJCDV1kJchyOeHQHxGpG/QGsdKks7ecwYIbP21PTi211wEAfTDTbo=
  - secure: hqbvnM936xcnv+G/irfsGCB+LxQyZRaeHaJgYoz8OpllpuWt0aKLudGtMbcAXinuHLXjq/TV3jtHYy7jRdr+bZlcxwDJZueu2Vi7DDR+NIDbN4wK400776U5vngDqjrEPnRkSYyw7Ofy4/NH1yXNopCcvi0UvtabN4bK4ogDPgJ3JGtBqiUSFiR8M7u48H4XrvUUGasTGiiiKRo8k0GO05KUdS0CT8QYpz7Qz4xj+CaqDbap1yn+sISwVde+cyVLd334KwaEIGbjF4YRUC2oUVXtZpAx66RmUf+qM4PmE0bXD4CWPu3Ed+WFxkPXsGEvPYY99jzytR6KCctlxeoPgmytaMPjKtxjdn+vCuJx0UH6JfZ2Cl8veftgnQW7LcGEiRpTaAfmqAe4iGxxWlPdZbDl8Pl4noee7CbsLq0Vw3r/a+SXvfi8jWn75IBz8IAaW11Hu33289e/vpPinsyk8NFkHWJd2sVU2riieAMNYMIs7TYAdMn6Hy1hLIZDgkRQXhz/wLfNk6t+3gd/Rh/j4d725WN3AW7l69jstUb5oWgcq2U9m+4M4I8SO+I/oH7K0q7TR9cZ1nOvwU13l8fLreq1F7Y9I0kNuVqi+QrUfZLSKmVwIQ8uqvxvWPXZPjAaNAp4Inl8IDJYWMK/+oBKGCGTZOwLrQYCSedn18eFNhY=
