language: php
php:
- '7.0'
sudo: required
dist: trusty
addons:
  ssh_known_hosts: 46.101.18.83
before_script:
- cp .env.travis .env
- mysql -e 'create database homestead;'
- composer install --no-interaction
- php artisan key:generate
- php artisan passport:keys
- php artisan migrate --seed --force
- sudo apt-get update && sudo apt-get install -y libxpm4 libxrender1 libgtk2.0-0 libnss3
  libgconf-2-4
- sudo apt-get install -y chromium-browser
- sudo apt-get install -y xvfb gtk2-engines-pixbuf
- sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
- sudo apt-get -y install imagemagick x11-apps
- Xvfb -ac :0 -screen 0 1280x1024x16 &
- chmod a+x ./vendor/laravel/dusk/bin/chromedriver-linux
- "./vendor/laravel/dusk/bin/chromedriver-linux --port=8888 &"
- php artisan serve &
before_deploy:
- openssl aes-256-cbc -K $encrypted_499e418efa07_key -iv $encrypted_499e418efa07_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --exclude storage --delete-after --quiet $TRAVIS_BUILD_DIR/* $DEPLOY_USER@$DEPLOY_IP:/var/www/$DEPLOY_DIR
  on:
    branch: 1.0/release
services:
- mysql
env:
  global:
  - secure: ev2cCC+UJ9FzSIvqbwEMGKDp+99pPxSyeXvStnVfm9ZcDA8Z27DquDWdtQ2mRldgVqLeGMO1efVbzBqbe4ZVGcTOLFFY5n3/AB6u+txZIhwr/oSX4qCYxDe/HTTMnyywrY59H33+MTnakjTsPxM2tgSWbN+bMz9BmeurZ7mnIQvz+1tBP1AhftoHw57wudoAM5KvK7ZHz6wEkwetq08MnOolleE7S1KCO7MCYmOdgjwqmIfdmTxq2AIiUqZmh1IKBjCDm76DPDDEwmcUyRH2wJtNR3aKWs73oQ6PUg2ZZxJdhxrhHqWUtxMnqNsz28srdDvJZ1MXywxYERO7zehOWICSjt/SwN83qBUI52zNLKeepaOptcx1DINO2nFcx1hq9fBWNWKgvpF6nBlu/mhd6gWjUYQzeHByVUudIhH82zlvcKcG5OrIOAsS26eJWnEyjsxN6jIKWPcIJlm1kU9TgMX6iTlfpIAFpkUIZ6rgxLCIbqO/8rCg2Z8IbqInaEYQZWAty/GnciuOLp08jjnHXsd+AsA/+MpSY2ysg9bnhNhwyK2GYgt6VsH5sMgdY/HbcIiwAnNNKcGwNoJnFBXfvIvsZ1SUOCwgf3lbav4bIpPxK8NnsNyOnXEYWF1Zr165KnZarPxEhPCp1CInHPV8YVVF97oP+YRS05apNrwOpVo=
  - secure: Vh0K8Zk2fQK4vr84EU8/Do8QVfEvNxtMgdYFI0TPJhqHZNQA7dqTIY7HBc/XVbtN2wvXET09/TEcj+iXfs+WEAmmhb/Ytww27x7vpuEv1f/k3C8H/3fkKPAvTNcvJR6AOPd8njk0d/wHKWN8bi81h/pX4hC7K8hgzgjlxaJ0a3dogMfniMi1aHYlRnoyWDU1Cc5hv/vdC8yXIF/j/dmtWgROuFQUGFFCVd43KNHvbjVlowPDwh2b3POGIByIYsjiBxiLo+yyCh9dlF52Amgyt9OuRhX4l2qQknVBSmCy4RYxEOBnYsvrETmkV9PyGsQxFOwdmBbPyvmlJkmzVDSVx4ljTsPeLKkWPxZde4JUqCofxxoe2BEWRcgmsReVrZsZJJPMKiW5fnM2fqd6WFIdx6zYxJ0nkCLSslIYE9pefGVDSFDhEgxnTjy0Z539kCpLEOCNaSqjmTXSczTPwZBIFgS6LvoFqgzH28NvNWOu8YsG9pS8t1zUHW0yyiixYsyuZP/HIjAI4eXXEjlo+jKQ3IboMYyc0lPHoRytD51xsxAuRJ2VljbgjDgrYGLpBDYy2JMGpP0bZNV8NRJI6qbfsUTsCS/JY4Ro4C8uWQ7RLngCim/TNlDtn4Ba6i4V/icvN3O9uEpcVgoSDp506TqYIvfkcTv0Sd7hh+FZKIkORvs=
  - secure: iBbwwNtA5KEESrcbA1Qsd+f1KjlDqHpVvXbPOzFgR4cnfjsJowmFYG2o7IjHnqbX1s80Ck1zIH2NcLbDgi919SIxC4BMltzn7zd0vm7Yi2YOe84HHZY+SiEAkvY92aACVkfXj8STGQa29Oxxn6RwBaatARelb5XKvNss8vB5wUb7DYQqbJYleSx2S707h+w6Zp6NZp3LVRWsEKHe7UpSaAMaig0j6x4bMqn8QzX/gMZW+/CQHDY7EUE6yCrX1ve+fIv2svH6nhosQhRKltnwHZMm38xfuHVBylSnykacVKqe5EeARKZ6FR0ueUfCkHyljZTK3odAuYrS1DbDBx4Eboi6+2bbJnFliqozq6/ElWk1W5J8OnkTtUSCulolsF5WSVI/0MDFKyx3RAGbufmrcMamyeA+BxSOfZ5r3aZfiUphc/Zg8Qr6aHqE6HMlBlks2SiFIUpwTc22K2PrF7WOEsoNIJCBoigP9aXSOECVas5KPiIiGM3piPnBgMki29xu/KkEI7KWETYCghGGKZN7aO367jUa4Y7xMZw+1V1j+dfhuwONPlTVPUasByu/ZKfaAyrz6KcYyZGqhBP7C3fDsCsNy0eE9MLnpH/GIsXawSuPLkGCYisoW+C0BdNPdR+M3bPBAP4zXd7YAsBBO0vZ0LKX9B3/kzcyr40d5hb2PtI=
