# See Docker.md for more info...
version: '2.1'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_DATABASE: lamp
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        # Uncomment this line to persist data between restarts
        #volumes:
            #- mysql:/var/lib/mysql
        restart: always
        healthcheck:
            test: ["CMD", "mysql" ,"-u", "lamp", "-plamp", "-h", "localhost", "lamp", "-e", "'desc user;'"]
            interval: 20s
            retries: 10

    arc:
        build:
            context: .
        image: neontribe/arc:dev
        environment:
            DB_USERNAME: lamp
            DB_PASSWORD: lamp
            DB_DATABASE: lamp
            DB_HOST: db
            DB_CONNECTION: mysql
            DB_PORT: 3306
        ports:
            - "8000:8000"
        extra_hosts:
            - host.docker.internal:host-gateway
            - arc.test:127.0.1.1
            - arcv-service.test:127.0.1.1
            - arcv-store.test:127.0.1.1
        # environment:
            # If you look in the docker file you can see what envs could be overridden
            # ARC_SERVICE_DOMAIN: arcv-service.test
            # ARC_STORE_DOMAIN: arcv-store.test
        volumes:
            - .:/opt/project
        depends_on: [ db ]
#         tty: true
#         stdin_open: true
#         entrypoint: bash
        links:
            - db
        restart: always

volumes:
    mysql:
