#!/bin/bash
set -e

# shellcheck source=/dev/null
source "$(dirname "$0")/bootstrap"

echo "===> Updating Composer dependencies..."
composer upgrade

echo "===> Updating npm dependencies..."
npm update
