version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=arcv
      - MYSQL_USER=arcvuser
      - MYSQL_PASSWORD=arcvpassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ../:/opt/project:ro

  service:
    image: arc-service:dev
    build:
      context: ..
      target: dev
    environment:
      - APP_URL=http://arcv-service.test
      - ARC_MARKET_URL=http://arcv-market.test
      - ARC_STORE_DOMAIN=arcv-store.test
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=arcv
      - DB_USERNAME=arcvuser
      - DB_PASSWORD=arcvpassword
      - LOG_CHANNEL=stderr
      - MAIL_HOST=mailer
      - MAIL_PORT=1025
      - SESSION_SECURE_COOKIE=false
    volumes:
      # this seems to overwrite the .env file that passport HAS to have as a file
      - ..:/opt/project
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "arcv-service.test:host-gateway"
      - "arcv-store.test:host-gateway"
      - "arcv-market.test:host-gateway"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_ADMIN_PORT:-2080}:1080"

volumes:
  service_public: