services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=arcv_service
      - MYSQL_USER=arcvuser
      - MYSQL_PASSWORD=arcvpassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    command: --default-storage-engine innodb
    restart: unless-stopped
    ports:
      - 3336:3306
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ../:/opt/project:ro
    restart: unless-stopped
    depends_on: [service]

  service:
    image: arc-service:dev
    build:
      context: ..
      target: dev
    environment:
      - APP_URL=http://arcv-service.test
      - ARC_MARKET_URL=http://arcv-market.test
      - ARC_STORE_DOMAIN=arcv-store.test
      - DB_CONNECTION=mysql
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_DATABASE=arcv_service
      - DB_USERNAME=arcvuser
      - DB_PASSWORD=arcvpassword
      - LOG_CHANNEL=stderr
      - MAIL_HOST=mailer
      - MAIL_PORT=1025
      - SESSION_SECURE_COOKIE=false
    volumes:
      # this seems to overwrite the .env file that passport HAS to have as a file
      - ..:/opt/project
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "arcv-service.test:host-gateway"
      - "arcv-store.test:host-gateway"
      - "arcv-market.test:host-gateway"
    restart: unless-stopped
    depends_on: [sqldb]

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_ADMIN_PORT:-2080}:1080"
    restart: unless-stopped

volumes:
  service_public:

# docker compose -f .docker/docker-compose.yml up -d
# docker compose -f .docker/docker-compose.yml logs -f
# docker compose -f .docker/docker-compose.yml exec service bash
# docker compose -f .docker/docker-compose.yml exec service /opt/project/artisan
# docker compose -f .docker/docker-compose.yml exec sqldb mysql -uarcvuser -parcvpassword arcv_service
