colorscheme elflord

" Code folding for bash
set nocompatible
filetype plugin indent on
set foldenable
set foldmethod=marker
au FileType sh let g:sh_fold_enabled=5
au FileType sh let g:is_bash=1
au FileType sh set foldmethod=syntax
syntax enable

syntax on
filetype indent on
set autoindent
set expandtab
set modeline
set shiftwidth=4
set smartindent
set tabpagemax=15
set tabstop=4

" Splits
nnoremap <C-Down> <C-W><C-J>
nnoremap <C-Up> <C-W><C-K>
nnoremap <C-Right> <C-W><C-L>
nnoremap <C-Left> <C-W><C-H>
set splitbelow
set splitright

" Map w!! to re-rwite as su
cmap w!! w !sudo tee % >/dev/null

" Tart up the cmd line
if has('cmdline_info') 
  set ruler
  set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%)
  set showcmd
endif

" Better searching
set showmatch
set incsearch
set hlsearch
set ignorecase
set smartcase
set wildmenu
set wildmode=list:longest,full
set scrolloff=3
" set list
" set listchars=tab:>.,trail:.,extends:#,nbsp:.
set pastetoggle=<F12>
set comments=sl:/*,mb:*,elx:*/

" Paste toggle
nnoremap <F12> :set invpaste paste?<CR>
set pastetoggle=<F12>
set showmode

" PHP globals
let php_parent_error_close = 1
let php_parent_error_open = 1
let php_folding = 1

" Have Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
  \| exe "normal! g'\"" | endif
endif
