name: Build and Push to Docker Hub

on:
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - main # Replace with your branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t arc/service:latest .
        docker push arc/service:latest
