name: Laravel

on:
  workflow_dispatch:
  push:
  # pull_request:
  #  branches: [ "1.16/release" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ghactions', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Create DB
      run: |
        touch /tmp/data.db
        php artisan migrate

    - name: Generate key
      run: php artisan key:generate

    - name: Passport install
      run: php .docker/passport-install.php .

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Key Permissions
      run: chmod 600 ./storage/*.key

    - name: Run tests
      run: |
       PHPUNIT_SKIP_MYSQL_TEST=1 XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-xml target/coverage

    - name: Check coverage
      run: |
       php artisan arc:test:coverage target/coverage/index.xml

# gh act -j test
