name: Test

on:
  workflow_dispatch:
#   push:
#     branches: [ "1.16/release" ]
#   pull_request:
#     branches: [ "1.16/release" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

#    services:
#      mysql:
#        image: mysql:8.0.21
#        env:
#          MYSQL_ALLOW_EMPTY_PASSWORD: yes
#          MYSQL_DATABASE: unittest
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Apt update
        run: sudo apt update

      - name: Install mysql
        run: sudo apt install -y mysql-client

      # https://github.com/marketplace/actions/setup-mysql
      - uses: mirromutth/mysql-action@v1.1
        with:
          container port: 3800
          mysql user: 'lamp'
          mysql password: 'lamp'

      - name: Verify DB exists
        run: mysql --host 127.0.0.1 --port 3800 -ulamp -plamp -e "SHOW DATABASES LIKE 'unittest'"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3800
          DB_USER: "lamp"
          DB_PASSWORD: "lamp"
          DB_DATABASE: "test"
        run: vendor/bin/phpunit
